IMG_SIZE=300
PREDICTION_PATH = "C:\\Users\\Theophile Bayet\\workspace\\THESIS\\GDS\\DATA\\DollarStreetDataset\\dataset_dollarstreet\\Benchmark_data\\info_CSRA_fuzzy.csv"
BENCHMARK_CSV_PATH =  "C:\\Users\\Theophile Bayet\\workspace\\THESIS\\GDS\\DATA\\DollarStreetDataset\\dataset_dollarstreet\\Benchmark_data\\CSRA\\Benchmark_CSRA_per_class.csv"
CLASS_CSV_PATH = "C:\\Users\\Theophile Bayet\\workspace\\THESIS\\GDS\\DATA\\DollarStreetDataset\\dataset_dollarstreet\\Benchmark_data\\CSRA\\Classes_report_CSRA.csv"
REPORT_CSV_PATH = ""
FUZZY_DIC = {
                'person':['teeth','hand palm','hand back'],
                'bicycle':['bike'],
                'car':['car'],
                'motorcycle':['moped/motorcycle'],
                'airplane':[],
                'bus':[],
                'train':[],
                'truck':[],
                'boat':[],
                'traffic_light':[],
                'fire_hydrant':[],
                'stop_sign':[],
                'parking_meter':[],
                'bench':[],
                'bird':['chickens'],
                'cat':[],
                'dog':[],
                'horse':[],
                'sheep':[],
                'cow':[],
                'elephant':[],
                'bear':[],
                'zebra':[],
                'giraffe':[],
                'backpack':[],
                'umbrella':[],
                'handbag':[],
                'tie':[],
                'suitcase':[],
                'frisbee':[],
                'skis':[],
                'snowboard':[],
                'sports_ball':[],
                'kite':[],
                'baseball_bat':[],
                'baseball_glove':[],
                'skateboard':[],
                'surfboard':[],
                'tennis_racket':[],
                'bottle':['alcoholic drinks'],
                'wine_glass':[],
                'cup':['cups/mugs/glasses'],
                'fork':[],
                'knife':['knifes'],
                'spoon':[],
                'bowl':[],
                'banana':[],
                'apple':[],
                'sandwich':[],
                'orange':[],
                'broccoli':[],
                'carrot':[],
                'hot_dog':[],
                'pizza':[],
                'donut':[],
                'cake':[],
                'chair':[],
                'couch':['couch','sofa'],
                'potted_plant':[],
                'bed':['bedroom','bed kids','guest bed','bed','children room'],
                'dining_table':['table with food'],
                'toilet':['bathroom/toilet','toilet'],
                'tv':['tv'],
                'laptop':['computer'],
                'mouse':[],
                'remote':[],
                'keyboard':[],
                'cell_phone':['phone'],
                'microwave':[],
                'oven':['oven','stove/hob'],
                'toaster':[],
                'sink':['kitchen sink'],
                'refrigerator':['refrigerator','freezer'],
                'book':['books'],
                'clock':['arm watch','wall clock'],
                'vase':[],
                'scissors':[],
                'teddy_bear':[],
                'hair_drier':[],
                'toothbrush':['toothbrush','toothpaste on toothbrush']
}
MATCH_CLS = [key for key,val in FUZZY_DIC.items() if val != []]
